DROP DATABASE IF EXISTS alunos;
CREATE DATABASE alunos;
USE alunos;

CREATE TABLE media(
	id INT AUTO_INCREMENT PRIMARY KEY,
	nome VARCHAR(100),
	codMatricula VARCHAR(100),
	nota1 FLOAT UNSIGNED,
	nota2 FLOAT UNSIGNED,
	nota3 FLOAT UNSIGNED,
	frequencia TINYINT UNSIGNED
);